version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8055:8080"
    environment:
      - SERVICES=s3
    volumes:
      - smax_hist_localstack:/var/lib/localstack

volumes:
  smax_hist_localstack:
